<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
	<RootNamespace>GameDevKit.Core</RootNamespace>
    <Nullable>enable</Nullable>
	<IsAotCompatible>true</IsAotCompatible>

	<Description>Primitive types and utilities</Description>
	<PackageTags>gamedev;game;core;gowelkin</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GameDevKit.Logging.Abstractions\GameDevKit.Logging.Abstractions.csproj" />
  </ItemGroup>

</Project>
