<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
	<RootNamespace>GameDevKit.Platforms.Steam</RootNamespace>
	<IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Facepunch.Steamworks" Version="2.3.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GameDevKit.Logging\GameDevKit.Logging.Abstractions.csproj" />
    <ProjectReference Include="..\GameDevKit.Networking.Abstractions\GameDevKit.Networking.Abstractions.csproj" />
    <ProjectReference Include="..\GameDevKit.Platforms\GameDevKit.Platforms.Abstractions.csproj" />
  </ItemGroup>
</Project>
