<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
	<RootNamespace>GameDevKit.Serialization.Abstractions</RootNamespace>
    <Nullable>enable</Nullable>

	<Description>Config contract</Description>
	<PackageTags>gamedev;serialization;json;config;gowelkin</PackageTags>
  </PropertyGroup>

</Project>
